### ISSUE TITLE
Hash Type List Empty

### ISSUE THREAD

**Issue by coolrecep** [s77rt/hashcat.launcher#34]
![image](https://user-images.githubusercontent.com/13221472/118400346-e8e3da00-b669-11eb-8b12-842b3ff8e1f7.png)

![image](https://user-images.githubusercontent.com/13221472/118400355-f13c1500-b669-11eb-9b17-c65967372c08.png)

Exe defined, latest version.

**Comment by foordeluxe** [comment]
I think that the current version of Hashcat.Launcher doesn't support Hashcat 6.2.1. Because I get the same bug.

**Comment by s77rt** [comment]
hashcat v6.2 has made some changes which are not supported yet, please try using hashcat v6.1
(also you need to type in the search box to get a list of hash types)

hashcat v6.2 will be supported soon

**Comment by s77rt** [comment]
fixed on master, try [building from source](https://github.com/s77rt/hashcat.launcher#building-from-source)

**Comment by sercanarga** [comment]
This bug has not been fixed yet.

**Comment by s77rt** [comment]
a pre-built (binary) has not been released yet, you can get it working only by building hashcat.launchjer from source
follow the commands on: https://github.com/s77rt/hashcat.launcher#building-from-source

**Comment by Joly0** [comment]
Can confirm its still not working. I build from master like explained and have hashcat version 6.2.1 but i cant select a hash type either 
![image](https://user-images.githubusercontent.com/13993216/120195377-0050c480-c21f-11eb-88ef-b747dd30d0c0.png)

**Comment by s77rt** [comment]
@Joly0 
i have tried again in windows and it's working, is it working for you now?
and can you replicate the issue?

**Comment by Joly0** [comment]
> @Joly0 
> i have tried again in windows and it's working, is it working for you now?
> and can you replicate the issue?
> 

Yes, its working for me. See my edit from my last message, was a problem with hashcat, not the launcher

**Comment by s77rt** [comment]
ah okay cool, thanks for the feedback

**Comment by s77rt** [comment]
hashcat.launcher.v0.5.2 is now available
